version: '3.8'
services:
  nest-app:
    container_name: financial-controller-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env